//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPUWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.CategoryNewsMappings = new HashSet<CategoryNewsMapping>();
        }
    
        public int Id { get; set; }
        public int CategoryOldId { get; set; }
        public string Code { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public int CategoryParentId { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> IsHome { get; set; }
        public string Images { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescrption { get; set; }
        public Nullable<int> TypeCategoryId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryNewsMapping> CategoryNewsMappings { get; set; }
    }
}
