//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPUWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailServer
    {
        public int MailServerId { get; set; }
        public string Host { get; set; }
        public string SenderMail { get; set; }
        public bool EnableSSL { get; set; }
        public string UserName { get; set; }
        public string DisplayName { get; set; }
        public string Password { get; set; }
        public string Port { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
