//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPUWeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public Nullable<bool> EmailConfirmaed { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Sex { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> PhoneNumberConfirmed { get; set; }
        public string Avata { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> LoginNewDate { get; set; }
        public Nullable<bool> LockoutEnabled { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Role Role { get; set; }
    }
}
