//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPUWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int ConfigId { get; set; }
        public string Logo { get; set; }
        public string GoogleAnanyticsId { get; set; }
        public string FacebookId { get; set; }
        public string GooglePlusId { get; set; }
        public string TwiterId { get; set; }
        public string YoutubeId { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Hotline { get; set; }
        public string SeoTitle { get; set; }
        public string SeoKeywords { get; set; }
        public string SeoDescription { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
