//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPUWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Categories = new HashSet<Category>();
            this.Users = new HashSet<User>();
        }
    
        public int DepartmentId { get; set; }
        public string Code { get; set; }
        public string DepartmentName { get; set; }
        public string Email { get; set; }
        public string PhomeNumber { get; set; }
        public string Photo { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string Note { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
