//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPUWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPUDataEntities : DbContext
    {
        public EPUDataEntities()
            : base("name=EPUDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Attactment> Attactments { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<CategoryNewsMapping> CategoryNewsMappings { get; set; }
        public DbSet<Config> Configs { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<MailServer> MailServers { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RoleFunction> RoleFunctions { get; set; }
        public DbSet<Slide> Slides { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<TypeCategory> TypeCategories { get; set; }
        public DbSet<TypeMenu> TypeMenus { get; set; }
        public DbSet<TypeSlide> TypeSlides { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
